services:
    postgres:
        image: postgres:17.5
        container_name: demo-postgres
        expose:
            - 5432
        environment:
            POSTGRES_DB: readingshare_db
            POSTGRES_USER: readingshare
            POSTGRES_PASSWORD: readingshare
        volumes:
            - postgres-data:/var/lib/postgresql/data
        restart: unless-stopped
        networks:
            - backend_db

    app:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: demo-app
        expose:
            - 8080
        environment:
            DB_HOST: postgres
            DB_PORT: 5432
            DB_USER: readingshare
            DB_PASS: readingshare
        depends_on:
            - postgres
        restart: unless-stopped
        networks:
            - backend
            - backend_db

    nodejs:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: demo-nodejs
        ports:
            - "80:80"
        depends_on:
            - app
        restart: unless-stopped
        networks:
            - frontend
            - backend

volumes:
    postgres-data:

networks:
    backend_db:
        internal: true
    backend:
        internal: true
    frontend:
