services:
    postgres:
        image: postgres:17.5
        container_name: demo-postgres
        expose:
            - 5432
        environment:
            POSTGRES_DB: readingshare_db
            POSTGRES_USER: readingshare
            POSTGRES_PASSWORD: readingshare
        volumes:
            - postgres-data:/var/lib/postgresql/data
        restart: unless-stopped
        networks:
            - backend

    app:
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: demo-springboot:latest
        container_name: demo-app
        expose:
            - 8080
        depends_on:
            - postgres
        restart: unless-stopped
        networks:
            - backend

    nginx:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: demo-nginx
        ports:
            - "80:80"
        depends_on:
            - app
        restart: unless-stopped
        networks:
            - frontend
            - backend

volumes:
    postgres-data:


networks:
    backend:
        internal: true
    frontend:
