services:
    postgres:
        image: postgres:17.5
        container_name: demo-postgres-dev
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: demo
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - postgres-data:/var/lib/postgresql/data
        restart: unless-stopped

volumes:
    postgres-data:
