spring:
    application:
        name: readingshare-system

    datasource:
        url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/readingshare_db
        username: ${DB_USER:readingshare}
        password: ${DB_PASS:readingshare}

    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
        # properties:
        #     "javax.persistence.schema-generation.scripts.action": "create"
        #     "javax.persistence.schema-generation.scripts.create-source": "metadata"
        #     "javax.persistence.schema-generation.scripts.create-target": "target/generated-schema.sql"
        #     "javax.persistence.schema-generation.scripts.drop-target": "target/drop-schema.sql"

    devtools:
        restart:
            enabled: false

    main:
        allow-circular-references: true
