spring:
    application:
        name: readingshare-system

    datasource:
        url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/readingshare_db
        username: ${DB_USER:readingshare}
        password: ${DB_PASS:readingshare}

    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false

    flyway:
        enabled: true
        locations: classpath:db/migration

    devtools:
        restart:
            enabled: false
